CREATE TABLE clients (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IP TEXT NOT NULL,
    TCP_PORT INTEGER NOT NULL,
    UDP_PORT INTEGER NOT NULL,
    NICKNAME TEXT NOT NULL,
    OPPONENT_ID INTEGER,
    UPDATED_AT INTEGER NOT NULL,
    FOREIGN KEY (OPPONENT_ID) REFERENCES clients(ID)
);